### ISSUE TITLE
[FEAT] Add logging limits to containers

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#603]
The logs for the fuseki service balloon to 500M just for the sandbox tests.  We need to limit the size of these.  The overloads say this is super easy. 

``` yaml
services:
  your_service_name:
    image: your_image
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```
